### PR TITLE
Chip component

### PR DESCRIPTION
**Pull request by unscsprt**
Addresses #646

### CODE REVIEW

**Comment by unscsprt** [comment]
[Chip](https://trello.com/c/UQCKNvzz/2-chip)

**Comment by unscsprt** [comment]
To give an update on progress here, I've gotten most of the basic functionality out of the way, but still need to get sign-off from @wesleymartin85.

- [ ] Sign-off for new component and its variations from design
- [ ] Add test coverage for `Chip`, fix failing tests
- [ ] Add new docs page

**Comment by wesleymartin85** [comment]
@unscsprt  let me know how you would like to review the component and its design variations. I am in NYC office today.

**Comment by jes708** [comment]
Could this component be added to v2 as well to help support backwards compatibility?

**Pull request closed without merging**
